### ISSUE TITLE
Error TASK: down atom editor

### ISSUE THREAD

**Issue by liam-ngy** [RefugeesOnRails/machina#13]
I tried to run the script on Mac(Linux recent version), but I got an error after the script tried to download Atom.

Fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed" to create temporary content file: (The read operation timed out)}

No More HOSTS LEFT
[Warning]: Could not create retry file 'site.retry'. [Errno 2] No such file or directory ''

PLAY RECAP
localhost: ok-17 changed-10 unreachable=0 failed=1

**Comment by sangyye** [comment]
Hello,
are you running on Ubuntu 14.04 or 16.04? 64bit? are there more of the error message? I need to see some more to be able to fix it.

regards

**Comment by sangyye** [comment]
Also it seems you have some permission or space problems on your Device. Is it possible that maybe the hard drive is full?
