### ISSUE TITLE
Add chromium to the installed software

### ISSUE THREAD

**Issue by jhilden** [RefugeesOnRails/machina#2]
I think having another browser can be very useful for web development

**Comment by sangyye** [comment]
Chrome is already part of the software bundle.

https://github.com/RefugeesOnRails/machina/blob/master/tasks/main.yml#L94

**Comment by jhilden** [comment]
hmm, weird I typed in "chrom" in the launcher on the test machine that I installed and nothing came up.  I will check it again next week.

But also, I would vote vor installing the open source version `chromium` instead of `chrome` in order to suport open source software.

The suggested packages would be: `'chromium-browser', 'chromium-codecs-ffmpeg'`

**Comment by sangyye** [comment]
I was just installing the packages @westonhankins want to have on the laptops

**Comment by sangyye** [comment]
@westonhankins what are you thinking about adding chromium, the opensource clone to the software list? But I was thinking, to reduce confusing we have to remove the official Chrome Browser. Why would you need two chrome browsers on the laptops?

**Comment by westonhankins** [comment]
@jhilden @sangyye I opted for Chrome as not all our students are already good techies and this would provide them the most similar experience to what they are already used to: print preview, easily play flash content, mp3 and other codecs, secure plugin marketplace, etc. They have enough to learn already - most of them never having used Ubuntu before.

**Comment by sangyye** [comment]
I would also vote for Chrome, for the reasons mention by @westonhankins.

@jhilden would it be okay for you that we leave the installation of chromium to the users, that really want it?

**Comment by jhilden** [comment]
sure, no problem
