### ISSUE TITLE
Chrome install failed on Ubuntu 14.04 64-bit clean install

### ISSUE THREAD

**Issue by Javachic** [RefugeesOnRails/machina#6]
TASK [add google chrome repo] **************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: , E:Some index files failed to download. They have been ignored, or old ones used instead.
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ror/.ansible/tmp/ansible-tmp-1461661135.97-29578995236821/apt_repository\", line 3322, in <module>\n    main()\n  File \"/home/ror/.ansible/tmp/ansible-tmp-1461661135.97-29578995236821/apt_repository\", line 471, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)\n, E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
    to retry, use: --limit @site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=7    unreachable=0    failed=1

**Comment by sangyye** [comment]
Fixed, sorry for the delay in response.
